### ISSUE TITLE
ERB incompatible character encodings error

### ISSUE THREAD

**Issue by chumaltd** [chumaltd/luca#1]
ERB takes templates as wrong character set in some environments.

```
(erb):9:in `render_erb': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
	from /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
	from /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
	from /usr/local/bundle/bundler/gems/luca-a3466c596706/lib/luca/io.rb:195:in `render_erb'
```

**Comment by chumaltd** [comment]
I found its cause is just locale settings. **ERB is affected by LANG** settings. The solution is as bellows.

* OS env is set LANG=ja_JP.UTF-8 or some UTF-8 variants. ASCII-8BIT is not human readable character set.
* File is properly encoded as UTF-8, of course.

I have set UTF-8 on some code & introduced magic comment, but no work.
I'll remove encoding from code because ruby default is UTF-8.
